spring.application.name=skatemap
spring.config.import=optional:file:env.properties
#${KY_URL}
spring.datasource.url=${KY_URL}
server.port=${PORT:3003}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}
# cloudflare
cloudflare.key.id=${CLOUDFLARE_KEY_ID}
cloudflare.app.key=${CLOUDFLARE_APP_KEY}
cloudflare.endpoint=${CLOUDFLARE_ENDPOINT}
cloudflare.region=${CLOUDFLARE_REGION}
cloudflare.bucket-raw=post-raw
cloudflare.bucket-processed=post-processed
cloudflare.public.url=https://pub-2041952f2a4b4563885e7dcacd123bdf.r2.dev
cloudflare.raw.url=https://pub-854c3b82595b453b97711ef3bc2bd2ca.r2.dev
# upload limit
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=30MB
# ai bot
spring.ai.openai.chat.lazy-init=true
spring.ai.openai.api-key:${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.max-tokens=500

#admin password
admin.password=${ADMIN_PASSWORD}
# stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.publishable.key=${STRIPE_PUBLISHABLE_KEY}
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.metrics.enabled=true

#####
# SERVER
spring.main.banner-mode=off

# DATABASE
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# JPA / HIBERNATE
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=false

# COMPRESSIONE
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html
server.compression.min-response-size=1024

# LOGGING
logging.level.root=WARN
logging.level.fra.skatemap=INFO
logging.level.org.hibernate=WARN
logging.level.org.springframework=WARN

# ACTUATOR
management.endpoints.enabled-by-default=false


