spring.application.name=skatemap
spring.config.import=optional:file:env.properties
#${KY_URL}
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
server.port=3003
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}
# CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_API_SECRET}
# MAILGUN
mailgun.domainName=${MAILGUN_DOMAIN_NAME}
mailgun.apiKey=${MAILGUN_API_KEY}
# upload limit
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
# ai bot
spring.ai.openai.api-key:${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.max-tokens=500

#admin password
admin.password=${ADMIN_PASSWORD}
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.metrics.enabled=true